### ISSUE TITLE
Homebridge service crashes

### ISSUE THREAD

**Issue by Zacknetic** [AchimPieters/Apple-Homebridge-Door-Lock#2]
After adding the sample config.json, homebridge now crashes on load.

This is my config.json. 

Also, what is the purpose of the username and password?
`{
    "bridge": {
        "name": "Homeblock",
        "username": "CC:40:3D:E3:CE:30",
        "port": 51826,
        "pin": "888-88-888"
    },

"description": "Homebridge Homeblock", "accessories": [
	{
			"accessory": "HttpLock",
			"name": "Door",
			"url": "http://192.168.1.10/",
			"lock-id": "1",
			"username": "Your_Username",
			"password": "Your_Password"
	}
]
}
`

**Comment by AchimPieters** [comment]
@Lethegrin 

I've checked your config.json in the [json validator](https://jsonlint.com) and it came out fine?
maybe there is something wrong with your home bridge installation, you can check the [site of the founder of this project here](https://github.com/nfarina/homebridge) for more information.

Regarding the username and password these are only necessary when you add a username and password in your home bridge configuration.

**Comment by Zacknetic** [comment]
I ended up just installing another http lock plugin which is working fine. I’m quite sure my homebridge is working as it only fails with this plugin and the provided config. 

Let me know if you want me to help you work out the bug, if any. Otherwise, I’m happy with my current setup.

**Comment by AchimPieters** [comment]
@Lethegrin 

Strange? what happens when you install the plugin? what do you see?

Help is always welcome! So yes, if you could help me that would be appreciated!

**Comment by Zacknetic** [comment]
Okay so the package installs correctly. However, when using the proper config setup as provided last post, homebridge fails starting up. Upon removal of your config, everything works fine. 

I can look at the error when I get home.
