### ISSUE TITLE
In sample config.json, HTTPLock

### ISSUE THREAD

**Issue by snarshad** [AchimPieters/Apple-Homebridge-Door-Lock#3]
Docs show 
`"accessory":` "HttpLock",

Sample config.json shows

`"accessory":` "Httplock",

However, when running Homebridge on macOS, these errors will appear:

```
Error: The requested accessory 'HttpLock' was not registered by any plugin.
Error: The requested accessory 'Httplock' was not registered by any plugin.

``` 

If I change it to "HTTPLock" it works.

`"accessory":` "HTTPLock",

**Comment by AchimPieters** [comment]
Thank you for placing this issue. I changed the typo. now it should work fine.
